#!/usr/bin/env node

const esbuild = require("esbuild");
const elmPlugin = require("esbuild-plugin-elm");
const { sassPlugin, postcssModules } = require("esbuild-sass-plugin");

const watch = process.argv.includes("--watch");
const isProduction = process.env.NODE_ENV === "production";

esbuild
  .build({
    entryPoints: ["./src/app.ts"],
    bundle: true,
    outdir: "./dist",
    minify: isProduction,
    watch,
    sourcemap: !isProduction && "inline",
    plugins: [
      elmPlugin({
        debug: !isProduction,
        optimize: isProduction,
        clearOnWatch: watch,
      }),
      sassPlugin({
        transform: postcssModules({ basedir: "./src/scss" }),
        sourceMap: !isProduction,
        type: "css",
      }),
    ],
  })
  .catch((_e) => process.exit(1));
