#!/usr/bin/env node

const path = require("path");

const esbuild = require("esbuild");
const copyStaticFilesPlugin = require("esbuild-copy-static-files");
const elmPlugin = require("esbuild-plugin-elm");
const { sassPlugin } = require("esbuild-sass-plugin");
const postcss = require("postcss");
const postcssPresetEnv = require("postcss-preset-env");

const watch = process.argv.includes("--watch");
const isProduction = process.env.NODE_ENV === "production";

const SRC_DIR = "./src";
const OUT_DIR = "./dist";
const STATIC_DIR = "./static";

function fromSource(localPath) {
  return path.resolve(SRC_DIR, localPath);
}

(function main() {
  esbuild
    .build({
      entryPoints: {
        app: fromSource("app.ts"),
        "assets/style/main": fromSource("scss/main.scss"),
      },
      bundle: true,
      outdir: OUT_DIR,
      minify: isProduction,
      watch,
      sourcemap: !isProduction && "inline",
      plugins: [
        copyStaticFilesPlugin({
          src: STATIC_DIR,
          dest: OUT_DIR,
        }),
        elmPlugin({
          debug: !isProduction,
          optimize: isProduction,
          clearOnWatch: watch,
        }),
        sassPlugin({
          type: "css",
          sourceMap: !isProduction,
          async transform(source, _) {
            const { css } = await postcss([
              postcssPresetEnv({ stage: 2 }),
            ]).process(source);
            return css;
          },
        }),
      ],
    })
    .catch(() => process.exit(1));
})();
