#!/usr/bin/env node

const esbuild = require("esbuild");
const ElmPlugin = require("esbuild-plugin-elm");

const watch = process.argv.includes("--watch");
const isProduction = process.env.NODE_ENV === "production";

esbuild
  .build({
    entryPoints: ["./src/app.js"],
    bundle: true,
    outdir: "./dist",
    minify: isProduction,
    watch,
    plugins: [
      ElmPlugin({
        debug: !isProduction,
        optimize: isProduction,
        clearOnWatch: watch,
      }),
    ],
  })
  .catch((_e) => process.exit(1));
